image:
  name: "registry.int.jrtashjian.com/homelab/terraform-images:master"

testing:
  stage: test
  before_script:
    - while read -r env_var; do
        export $env_var=$(op read "$(printenv "$env_var")");
      done < <(op env ls)
  script:
    - op user get --me
    - printenv

