include:
  - project: 'homelab/terraform-images'
    file: '/templates/Base.gitlab-ci.yml'

image:
  name: "$CI_REGISTRY/homelab/terraform-images/releases/terraform:1.7.2"

.nodes:
  parallel:
    matrix:
      - TF_STATE_NAME: "pve-node01"
        TF_VAR_node_datastore: "local-lvm"
      - TF_STATE_NAME: "pve-node02"
        TF_VAR_node_datastore: "machines"
      - TF_STATE_NAME: "pve-node03"
        TF_VAR_node_datastore: "machines"

variables:
  ONEPASSWORD_BINARY_VERSION: "2.24.0"
  PROXMOX_VE_ENDPOINT: "https://${TF_STATE_NAME}.int.jrtashjian.com:8006"
  TF_VAR_node_name: "${TF_STATE_NAME}"

before_script:
  - curl -sLo op.zip "https://cache.agilebits.com/dist/1P/op2/pkg/v${ONEPASSWORD_BINARY_VERSION}/op_linux_amd64_v${ONEPASSWORD_BINARY_VERSION}.zip"
  - unzip op.zip
  - rm op.zip
  - mv ./op /usr/local/bin/op
  - op --version
  - terraform --version
  - terraform init -input=false

stages:
  - validate
  - build
  - deploy
  - cleanup

fmt:
  extends: .terraform:fmt
  needs: []

validate:
  extends: .terraform:validate
  needs: []

build:
  extends:
    - .terraform:build
    - .nodes
  environment:
    name: "${TF_STATE_NAME}"
    action: prepare

cleanup:
  extends:
    - .terraform:destroy
    - .nodes
  environment:
    name: "${TF_STATE_NAME}"
    action: stop
