image:
  name: "registry.int.jrtashjian.com/homelab/terraform-images/releases/1.7:latest"

variables:
  ONEPASSWORD_BINARY_VERSION: "2.24.0"

testing:
  stage: test
  before_script:
    - curl -sLo op.zip "https://cache.agilebits.com/dist/1P/op2/pkg/v${ONEPASSWORD_BINARY_VERSION}/op_linux_amd64_v${ONEPASSWORD_BINARY_VERSION}.zip"
    - unzip op.zip
    - rm op.zip
    - mv ./op /usr/local/bin/op
    - op --version
  script:
    - op user get --me
    - op run -- printenv